server:
  port: ${GATEWAY_PORT:8443}

spring:
  application:
    name: flexi-gate
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddRequestHeader=X-Default-Header, DefaultValue
          metrics:
            enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:${EUREKA_PORT:8761}/eureka/

# ⬅️ management à la RACINE, pas sous spring
management:
  server:
    port: 8444
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: never
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    # Gateway principal
    org.springframework.cloud.gateway: ${LOG_LEVEL_GATEWAY:ERROR}
    org.springframework.cloud.gateway.handler: ${LOG_LEVEL_GATEWAY:ERROR}
    org.springframework.cloud.gateway.route: ${LOG_LEVEL_GATEWAY:ERROR}

    # Web & WebSocket
    org.springframework.web: ${LOG_LEVEL_WEB:ERROR}
    org.springframework.web.socket: ${LOG_LEVEL_WEB:ERROR}
    org.springframework.web.reactive: ${LOG_LEVEL_WEB:ERROR}
    org.springframework.web.reactive.socket: ${LOG_LEVEL_WEB:ERROR}
    org.springframework.http.server.reactive: ${LOG_LEVEL_WEB:ERROR}

    # Reactor Netty (server)
    reactor.netty: ${LOG_LEVEL_NETTY:ERROR}
    reactor.netty.http.client: ${LOG_LEVEL_NETTY:ERROR}
    reactor.netty.http.server: ${LOG_LEVEL_NETTY:ERROR}

    # Headers & Requests detailed
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: ${LOG_LEVEL_REQUEST:ERROR}

    # Discovery (if used)
    org.springframework.cloud.client.discovery: ${LOG_LEVEL_DISCO:ERROR}

  # Pattern for stdout
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"