server:
  port: ${GATEWAY_PORT:8443}

spring:
  application:
    name: flexi-gate
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddRequestHeader=X-Default-Header, DefaultValue

eureka:
  client:
    service-url:
      defaultZone: http://eureka:${EUREKA-PORT:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: never
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO
    org.springframework.cloud.client.discovery.simple: INFO
    reactor.netty.http.client: INFO